# Jimple 블로그 설정
# 블로그 기본 정보
title: "Test Blog"        # 블로그 제목
description: "Welcome My Blog"     # 블로그 설명 (메타태그 용)
logo: ""

# 레이아웃 설정
layout:
  # 메뉴 위치: 'top', 'left', 'right' 중 하나
  menuPosition: "top"
  welcome:
    show: true
    title: "<h1><span class=\"bold\">Welcome to</span> <span class=\"gradient-text\">My Blog</span></h1>"
    comment: "<p class=\"subtitle\">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>"

  # 색상 테마
  colors:
    primary: "#4a86e8"       # 주 색상 (헤더, 강조 등)
    secondary: "#63c5da"     # 보조 색상
    background: "#ffffff"    # 배경 색상
    text: "#333333"          # 본문 텍스트 색상
    headings: "#222222"      # 제목 텍스트 색상
    links: "#0366d6"         # 링크 색상

# 프로필 정보
profile:
  name: "홍길동"              # 이름
  role: "소프트웨어 개발자"     # 직함/역할
  bio: "Java와 웹 개발에 관심이 많은 개발자입니다."  # 간단한 소개
  social:
    - platform: "github"
      url: "https://github.com/username"
    - platform: "twitter"
      url: "https://twitter.com/username"
    - platform: "linkedin"
      url: "https://linkedin.com/in/username"

# 추가 커스터마이징 옵션
customization:
  showDate: true             # 게시물 날짜 표시 여부
  enableComments: false      # 댓글 기능 활성화 여부
  footerText: "© 2025 Test Blog. All rights reserved."  # 푸터 텍스트