package com.jimple.generator;

import com.jimple.generator.converter.Md2HtmlConverter;
import com.jimple.model.MarkdownFile;

public class SimpleMarkdownGenerator implements MarkdownGenerator {
    private final Md2HtmlConverter converter;

    public SimpleMarkdownGenerator(Md2HtmlConverter converter) {
        this.converter = converter;
    }

    @Override
    public String generateToHtml(MarkdownFile file) {
        if (file == null || !file.isPublish()) {
            return "";
        }

        String headerHtml = converter.convertHeaderToHtml(file.properties());
        String contentHtml = converter.convertBodyToHtml(file.contents());
        String combinedContent = headerHtml + contentHtml;
        
        return wrapWithHtmlBoilerplate(combinedContent, file.properties().title());
    }
    
    private String wrapWithHtmlBoilerplate(String content, String title) {
        return """
                <!DOCTYPE html>
                <html lang="ko">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>%s</title>
                    <link rel="stylesheet" href="/assets/jimple.css" >
                </head>
                <body>
                    <article>
                        %s
                    </article>
                    <footer>
                        <p>Generated by Jimple</p>
                    </footer>
                </body>
                </html>
                """.formatted(title, content);
    }
}