# .github/workflows/native-build.yml
name: Build GraalVM Native Binaries

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '릴리스 태그를 입력하세요 (예: v1.2.3)'
        required: true
        default: 'v0.0.1'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build on ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: 'native-image'

      - name: Build Native Image
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ./mvnw.cmd -Pnative package
          else
            ./mvnw -Pnative package
          fi
        shell: bash

      - name: Rename binary (optional)
        run: |
          mkdir dist
          mv ./target/jimple dist/jimple-${{ matrix.os }}
        shell: bash

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}